In [15]:
# o objetivo é criar um novo arquivo com as mudanças que desejo
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [7]:
# mostrando como o arquivo original esta
Arq_old = pd.read_csv('/home/alison/Projetos/Projeto-udemy-MachineLearning/DataSets/Datasets de treino/GSM2070024_sample_table.txt',
                     delimiter='\t')
Arq_old

         ID_REF      VALUE
0      16650001   2.331780
1      16650003   1.615470
2      16650005   3.160910
3      16650007   2.026290
4      16650009   0.888439
5      16650011   2.478870
6      16650013   3.622990
7      16650015   4.913320
8      16650017   2.772310
9      16650019   3.036540
10     16650021   3.356050
11     16650023   1.299900
12     16650025   2.957100
13     16650027   2.733090
14     16650029   3.839550
15     16650031   1.877440
16     16650033   0.872530
17     16650035   1.727220
18     16650037   1.762660
19     16650041   4.829310
20     16650043   4.775430
21     16650045   2.717110
22     16650047   3.376590
23     16650049   1.468360
24     16650051   2.806540
25     16650053   5.205050
26     16650055   2.581350
27     16650057   4.160640
28     16650059   6.165000
29     16650061   1.072150
...         ...        ...
53587  16934242   2.065330
53588  16934243   2.367990
53589  16934244   7.074120
53590  16934245   8.602280
53591  16934246   7.425850
53592  16934247   7.430210
53593  16934584   6.379590
53594  16934585   5.718010
53595  16934586  10.291800
53596  16934587  10.811000
53597  16934588   5.313330
53598  16934589   6.379590
53599  16934590   9.758660
53600  16934591   8.014090
53601  16934592   2.734630
53602  16934593   7.186240
53603  16934594  10.860700
53604  16934595   7.135830
53605  16934596  10.110400
53606  16934597  11.135000
53607  16934598  11.162200
53608  16934600   9.662470
53609  16934601  10.720100
53610  16934602  10.064100
53611  16934603  10.625400
53612  16934604   3.468640
53613  16934607   6.162640
53614  16934608   3.703520
53615  16934609   3.896380
53616  16934610   2.557180

[53617 rows x 2 columns]

In [10]:
# a linha do with abre o arquivo original
# é importante que que eu mude o nome do arquivo de parametro no arq = open(''), se não o arquivo original será 
# alterado
with open('/home/alison/Projetos/Projeto-udemy-MachineLearning/DataSets/Datasets de treino/GSM2070024_sample_table.txt', 'r') as f:
    # a linha abaixo cria um novo arquivo com extensão .csv já com as mudanças que desejo
    arq = open('/home/alison/Projetos/Projeto-udemy-MachineLearning/DataSets/Datasets de treino/GSM2070024_sample_table.csv','a')
    for linha in f.readlines():
        arq.write(linha.replace('\t', ';'))
    arq.close()

In [18]:
with open('/home/alison/Projetos/Projeto-udemy-MachineLearning/DataSets/Datasets de treino/GSM2070024_sample_table.csv','r') as f:
    grafico = np.array(f)
    len(grafico.all)

TypeError: object of type 'builtin_function_or_method' has no len()